config/routes.rb
Rails.application.routes.draw do
  get 'products/the88laws'

  devise_for :users
  resources :posts
  resources :subscribers
  get 'pages/videos'

root 'pages#home'

get "about" => 'pages#about'
get "Home" => 'pages#home'
get "blog" => 'pages#blog'

get "products" => 'pages#products'

get "videos" => 'pages#videos'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :profile_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def videos
  end

  def home
  end

  def about
  end

  def products
  end

  def blog
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def the88laws
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/layouts/_footer.html.erb
</br></br>
    <!-- FOOTER
    ============================== -->
    <footer>

      <!-- Footer Top -->
      <div class="footer_top hidden-xs">
        <div class="container">
          <div class="row">

            <!-- Contact Us -->
            <div class="col-xs-12 col-sm-3">
              <div class="footer__item">
                <div class="footer__title">Contact Us</div>
                <div class="footer__content">
                  <p>
                    Do not hesitate to contact us if you have any questions or requests:
                  </p><p>
                   <br><br>
                  </p><p>
                    Phone: +0 000-000-0000<br>
                    Fax: +0 000 000 00 00
                  </p><p>
                    Email: <a href="#">support@10xPickup.com</a>
                  </p>
                </div>
              </div>
            </div>

            <!-- Recent Tweets -->
            <div class="col-xs-12 col-sm-3">
              <div class="footer__item">
                <div class="footer__title">Recent Tweets</div>
                <div class="footer__content">
                  <div class="footer__tweet">
                    <div class="footer-tweet__icon">
                      <i class="fa fa-twitter"></i>
                    </div>
                    <div class="footer-tweet__content">
                      <p>
                        <a href="#">@10xPickup</a> Differenciate or Die
                      </p>
                      <a href="#">1 hour ago</a>
                    </div>
                  </div>
                  <div class="footer__tweet">
                    <div class="footer-tweet__icon">
                      <i class="fa fa-twitter"></i>
                    </div>
                    <div class="footer-tweet__content">
                      <p>
                        <a href="#">@10xPickup</a> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmo
                      </p>
                      <a href="#">1 day ago</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- Recent Posts -->
            <div class="col-xs-12 col-sm-3">
              <div class="footer__item">
                <div class="footer__title">Recent Posts</div>
                <div class="footer__content">
                  <div class="footer__post">
                    <div class="footer-post__img">
                      <%= image_tag 'general_1.jpg' %>
                    </div>
                    <div class="footer-post__content">
                      <p><a href="#">Lorem ipsum dolor sit amet</a></p>
                      <time datetime="2015-01-01">2015/01/01</time>
                    </div>
                  </div>
                  <div class="footer__post">
                    <div class="footer-post__img">
                      <%= image_tag 'general_2.jpg' %>
                    </div>
                    <div class="footer-post__content">
                      <p><a href="#">Lorem ipsum dolor sit amet</a></p>
                      <time datetime="2015-01-01">2015/01/01</time>
                    </div>
                  </div>
                  <div class="footer__post">
                    <div class="footer-post__img">
                      <%= image_tag 'general_3.jpg' %>
                    </div>
                    <div class="footer-post__content">
                      <p><a href="#">Lorem ipsum dolor sit amet</a></p>
                      <time datetime="2015-01-01">2015/01/01</time>
                    </div>
                  </div>
                </div>
              </div>            
            </div>

            <!-- Quick Links -->
            <div class="col-xs-12 col-sm-3">
              <div class="footer__item">
                <div class="footer__title">Quick Links</div>
                <div class="footer__content">
                  <ul class="footer__links">
                    <li><a href="#">Donec commodo turpis eget orci</a></li>
                    <li><a href="#">Lorem ipsum dolor sit amet</a></li>
                    <li><a href="#">Aenean rhoncus vel nisi sed</a></li>
                    <li><a href="#">Aenean accumsan volutpat libero</a></li>
                    <li><a href="#">Vestibulum lacinia erat massa</a></li>
                  </ul>
                </div>
              </div>            
            </div>

          </div> <!-- / .row -->
        </div> <!-- / .container -->
      </div> <!-- / .footer_top -->
      <div class="footer__hr hidden-xs"></div>

      <!-- Footer Bottom -->
      <div class="footer_bottom">
        <div class="container">
          <div class="row">
            <div class="col-xs-12 col-sm-6">
              <div class="footer__copyright">
                Copyright 2016 <a href="http://10xPickup.com">10xPickup.com</a>. All Rights Reserved.
              </div>
            </div>
            <div class="col-xs-12 col-sm-6">
              <ul class="footer__social">
                <li class="twitter"><a href="https://twitter.com/10xPickup"><i class="fa fa-twitter"></i></a></li>
                <li class="facebook"><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li class="linkedin"><a href="#"><i class="fa fa-linkedin"></i></a></li>
                <li class="google-plus"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                <li class="pinterest"><a href="#"><i class="fa fa-pinterest"></i></a></li>
              </ul>
            </div>
          </div> <!-- / .row -->
        </div> <!-- / .container -->
      </div> <!-- / .footer_bottom -->
    </footer>


app/views/layouts/_navbar.html.erb


    <!-- STATIC TOPBAR
    ============================== -->
    <div class="topbar hidden-xs hidden-sm">
      <div class="container">
        <!-- Social links -->
        <ul class="topbar-nav topbar-nav_left">
          <li><a href="https://twitter.com/10xPickup"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          <li><a href="#"><i class="fa fa-vk"></i></a></li>
          <li><a href="#"><i class="fa fa-stumbleupon"></i></a></li>
        </ul>
        <ul class="topbar-nav topbar-nav_right">

          <!-- Account links -->

          <% if user_signed_in? %>
          <li><%= link_to "Profile", edit_user_registration_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %> </li>
            <% else %>
          <li><%= link_to "Sign-in", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>
      </div> <!-- / .container -->
    </div> <!-- / .topbar -->
    <div class="navbar__hr hidden-xs hidden-sm"></div>


    <!-- STATIC NAVBAR
    ============================== -->
    <div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <!-- Toggle button -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- Brand name -->
          <%= link_to image_tag("thelogoo.png"), root_path, class:"navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse">
          <!-- Navbar links -->
          <ul class="nav navbar-nav navbar-right">

            <!-- Home -->
            <li class="dropdown">
             <%= link_to 'Home', root_path %>

            </li>


            <!-- Portfolio -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                About <span class="fa fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'About', about_path %></li>
                <li><a href="portfolio-item.html">Portfolio</a></li>
              </ul>
            </li>

                        <!-- Portfolio -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                videos <span class="fa fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Videos', videos_path %></li>
              </ul>
            </li>
            <!-- Blog -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Articles <span class="fa fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Articles', blog_path %></li>
                <li><%= link_to 'Blog', blog_path %></li>
                <li><%= link_to 'Posts', posts_path %></li>
              </ul>
            </li>

            <!-- Shop -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Products <span class="fa fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Products', products_path %></li>
                <li><a href="shop-item.html">Shop Item</a></li>
                <li><a href="shopping-cart.html">Shopping Cart</a></li>
              </ul>




            <!-- Profile -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Profile <span class="fa fa-angle-down"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li class="dropdown-submenu">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign In</a>
                  <!-- Dropdown submenu -->
                  <ul class="dropdown-menu">
                    <li><a href="sign-in.html">Sign In: Default</a></li>
                    <li><a href="sign-in_option-1.html">Sign In: Option 1</a></li>
                  </ul>
                </li>
                <li class="dropdown-submenu">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign Up</a>
                  <!-- Dropdown submenu -->
                  <ul class="dropdown-menu">
                    <li><a href="sign-up.html">Sign Up: Default</a></li>
                    <li><a href="sign-up_option-1.html">Sign Up: Option 1</a></li>
                  </ul>
                </li>
                <li><a href="profile.html">User Profile</a></li>
              </ul>
            </li>


            
            </li>


        </div> <!-- / .navbar-collapse -->
      </div> <!-- / .container -->
    </div> <!-- / .navbar -->


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Official 10xPickup | Shah Daymond</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>

   <body class="body_index">
   		

		<%= render "layouts/navbar" %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
		<%= yield %>

		<%= render "layouts/footer" %>

	</body>
</html>

app/views/pages/blog.html.erb
    <!-- PAGE HEADER
    ============================== -->
    <div class="page__header">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <h3 class="page-header__title">Blog</h3>
            <ol class="breadcrumb page-header__breadcrumb">
              <li><a href="index.html">Home</a></li>
              <li class="active">Blog</li>
            </ol>
          </div>
        </div>
      </div>
    </div>


    <!-- PAGE CONTENT
    ============================== -->
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-9">
          <div class="blog__items">
            <div class="blog__item">
              <%= image_tag 'general_1.jpg', class:'img-responsive blog__img hidden-x' %>
              <div class="blog__content">
                <h3 class="blog__title">
                  <a href="blog-post.html">Sed lacinia suscipit lacus non sodales. Pellentesque lacinia ornare justo eu tincidunt</a>
                </h3>
                <ul class="blog__info">
                  <li><time datetime="2015-01-30">January 30, 2015</time></li>
                  <li><a href="#">Bootstrap</a></li>
                  <li><a href="#"><i class="fa fa-comments-o"></i> 2</a></li>
                </ul>
                <div class="blog__body">
                  Nam ultrices, orci sit amet dignissim dignissim, tellus elit consequat dui, eu venenatis urna nisi non est. Aliquam egestas pulvinar ornare. Aenean et vulputate lacus. Ut eget purus ut ante imperdiet feugiat quis vel elit. Donec imperdiet enim quis risus porttitor congue. Vestibulum vel tristique urna. Pellentesque nulla leo, laoreet sed luctus eu, dapibus id lorem. Pellentesque eu tincidunt odio. Proin imperdiet bibendum mauris, ut bibendum odio mollis id.
                </div>
              </div>
              </br></br>
            </div> <!-- / .blog__item -->
            <div class="blog__item">
              <%= image_tag 'general_2.jpg', class:'img-responsive blog__img hidden-x' %>
              <div class="blog__content">
                <h3 class="blog__title">
                  <a href="blog-post.html">Ut eget purus ut ante imperdiet feugiat quis vel elit. Donec imperdiet enim quis risus</a>
                </h3>
                <ul class="blog__info">
                  <li><time datetime="2015-01-29">January 29, 2015</time></li>
                  <li><a href="#">Bootstrap</a></li>
                  <li><a href="#"><i class="fa fa-comments-o"></i> 4</a></li>
                </ul>
                <div class="blog__body">
                  Nam ultrices, orci sit amet dignissim dignissim, tellus elit consequat dui, eu venenatis urna nisi non est. Aliquam egestas pulvinar ornare. Aenean et vulputate lacus. Ut eget purus ut ante imperdiet feugiat quis vel elit. Donec imperdiet enim quis risus porttitor congue. Vestibulum vel tristique urna. Pellentesque nulla leo, laoreet sed luctus eu, dapibus id lorem. Pellentesque eu tincidunt odio. Proin imperdiet bibendum mauris, ut bibendum odio mollis id.
                </div>
              </div>
            </div> <!-- / .blog__item -->
            </br></br>
            <%= image_tag 'general_3.jpg', class:'img-responsive blog__img hidden-x' %>
              <div class="blog__content">
                <h3 class="blog__title">
                  <a href="blog-post.html">Donec imperdiet enim quis risus porttitor congue. Vestibulum vel tristique urna</a>
                </h3>
                <ul class="blog__info">
                  <li><time datetime="2015-01-28">January 28, 2015</time></li>
                  <li><a href="#">Design</a></li>
                  <li><a href="#"><i class="fa fa-comments-o"></i> 1</a></li>
                </ul>
                <div class="blog__body">
                  Nam ultrices, orci sit amet dignissim dignissim, tellus elit consequat dui, eu venenatis urna nisi non est. Aliquam egestas pulvinar ornare. Aenean et vulputate lacus. Ut eget purus ut ante imperdiet feugiat quis vel elit. Donec imperdiet enim quis risus porttitor congue. Vestibulum vel tristique urna. Pellentesque nulla leo, laoreet sed luctus eu, dapibus id lorem. Pellentesque eu tincidunt odio. Proin imperdiet bibendum mauris, ut bibendum odio mollis id.
                </div>
              </div>
            </div> <!-- / .blog__item -->

            </br></br>
            <%= image_tag 'general_6.jpg', class:'img-responsive blog__img hidden-x' %>
              <div class="blog__content">
                <h3 class="blog__title">
                  <a href="blog-post.html">Proin imperdiet bibendum mauris, ut bibendum odio mollis id</a>
                </h3>
                <ul class="blog__info">
                  <li><time datetime="2015-01-27">January 27, 2015</time></li>
                  <li><a href="#">Coding</a></li>
                  <li><a href="#"><i class="fa fa-comments-o"></i> 6</a></li>
                </ul>
                <div class="blog__body">
                  Nam ultrices, orci sit amet dignissim dignissim, tellus elit consequat dui, eu venenatis urna nisi non est. Aliquam egestas pulvinar ornare. Aenean et vulputate lacus. Ut eget purus ut ante imperdiet feugiat quis vel elit. Donec imperdiet enim quis risus porttitor congue. Vestibulum vel tristique urna. Pellentesque nulla leo, laoreet sed luctus eu, dapibus id lorem. Pellentesque eu tincidunt odio. Proin imperdiet bibendum mauris, ut bibendum odio mollis id.</br></br>
                </div>
              </div>
            </div> <!-- / .blog__item -->
          </div> <!-- / .blog__items -->
          <!-- Pager -->
          <ul class="pager pull-right">
            <li class="disabled"><a href="#">Previous</a></li>
            <li><a href="#">Next</a></li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="col-sm-4 col-md-3">

          <!-- Recommended & Popular -->
          <h3 class="header header_plain">More Stories</h3>
          <ul class="nav nav-tabs nav-justified" role="tablist">
            <li role="presentation" class="active">
              <a href="#blog-tab_recommended" aria-controls="blog-tab_recommended" role="tab" data-toggle="tab">Recommended</a>
            </li>
            <li role="presentation">
              <a href="#blog-tab_popular" aria-controls="blog-tab_popular" role="tab" data-toggle="tab">Popular</a>
            </li>
          </ul>
          <div class="tab-content">
            <!-- Recommended -->
            <div role="tabpanel" class="tab-pane active" id="blog-tab_recommended">
              <div class="list-group blog-tab__list">
                <a href="#" class="list-group-item">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit
                  <time datetime="2015-01-01">January 1, 2015</time>
                </a>
                <a href="#" class="list-group-item">
                  Cras hendrerit tellus porttitor elementum commodo
                  <time datetime="2015-01-02">January 2, 2015</time>
                </a>
                <a href="#" class="list-group-item">
                  Sed ultrices euismod hendrerit. Nunc augue tellus
                  <time datetime="2015-01-03">January 3, 2015</time>
                </a>
                <a href="#" class="list-group-item">
                  Maecenas venenatis sodales sem
                  <time datetime="2015-01-04">January 4, 2015</time>
                </a>
              </div>
            </div>
            <!-- Popular -->
            <div role="tabpanel" class="tab-pane" id="blog-tab_popular">
              <div class="list-group blog-tab__list">
                <a href="#" class="list-group-item">
                  Sed ultrices euismod hendrerit. Nunc augue tellus
                  <time datetime="2015-01-05">January 5, 2015</time>
                </a>
                <a href="#" class="list-group-item">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit
                  <time datetime="2015-01-06">January 6, 2015</time>
                </a>
                <a href="#" class="list-group-item">
                  Maecenas venenatis sodales sem
                  <time datetime="2015-01-07">January 7, 2015</time>
                </a>
                <a href="#" class="list-group-item">
                  Cras hendrerit tellus porttitor elementum commodo
                  <time datetime="2015-01-08">January 8, 2015</time>
                </a>
              </div>
            </div>
          </div>
        </div> 
      </div> <!-- / .row -->
    </div> <!-- / .container -->
    
    </br>    </br>    </br>    </br>    </br>    </br>    </br>    </br>

app/views/pages/videos.html.erb
<h1>Pages#videos</h1>
<p>Find me in app/views/pages/videos.html.erb</p>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>



<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>



<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
         <td><%= post.user.email %></td>
        <td><%= link_to 'Show', post %></td>
        <% if post.user == current_user %>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>


<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>
		<%= link_to 'Edit', edit_post_path(@post) %> |

		<%= link_to 'Back', posts_path %>





<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>